---
# tasks file for role_nfs
- name: NFS server installed
  yum:
    name:
      - nfs-utils
      - nfs4-acl-tools
    state: present

- name: share directory exists
  file:
    path: "{{ share }}"
    state: directory
    mode: "{{ permission }}"
    owner: root
    group: root

- name: share in /etc/exports file
  lineinfile:
    path: /etc/exports
    state: present
    line: '{{ share }} {{ options }}'
  notify: restart NFS server
  
- name: restart NFS server
  service:
    name: nfs-server
    state: restarted
    enabled: true

- name: export share
  command: "exportfs -arv"
  
- name: check share
  command: "exportfs -s"

- name: configurar firewall
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - nfs
    - rpc-bind
    - mountd


        
