---
# tasks file for role_master

- name: 'Establecer nombre de host'
  hostname:
    name: "{{ nombre_dominio }}"
    use: systemd
  tags: master

- name: 'Establecer IP interna'
  set_fact:
    ip_interna: "{{ ansible_facts['default_ipv4']['address'] }}"
  tags: master

- debug:
    var: ip_interna
  tags: master